-- Define the Database
use Project__01

/* 
 Q1. What is the total revenue generated by male vs. female customer?
 Q2. Which customers used a discount but still spent more than the average purchase amount?
 Q3. Which are the top 5 products with the highest average review rating?
 Q4. Compare the average purchase amounts between standered and Express shipping .
 Q5. Do subscribe customers spend more? Compare average spend and total revenue between subscribers and non-subscribers/
 Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 Q7. Segment customers into New , Retruening , adn Loyal based on hteir total number of previous purchases , 
 Q8. What are the top 3 most purchased products within each category?
 Q9. Are customers who are reat buyers (more than 5 previous purchases ) also likely to subscriber?
 Q10. What is the revenue contribution of each age group?

*/


-- round up the review_rating value
SELECT TOP 10 * FROM cust_shop_beha

ALTER TABLE cust_shop_beha
ADD review_ratings FLOAT;
SELECT ROUND(review_rating,2) FROM cust_shop_beha

INSERT INTO  cust_shop_beha(Review_Ratings)
SELECT (SELECT ROUND(review_rating,2) FROM cust_shop_beha) 
FROM cust_shop_beha


-- Q1. What is the total revenue generated by male vs. female customer?

SELECT
	Gender,SUM(Purchase_Amount_USD) AS revenue
FROM cust_shop_beha
GROUP BY Gender



 -- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
	Customer_ID,SUM(Purchase_Amount_USD) AS Total_spent
FROM cust_shop_beha
WHERE UPPER(Discount_Applied) = 'YES' AND Purchase_Amount_USD >= (SELECT AVG(Purchase_Amount_USD) FROM cust_shop_beha)
GROUP BY Customer_ID



--  Q3. Which are the top 5 products with the highest average review rating?
SELECT  TOP 5
	Item_Purchased,ROUND(AVG(review_rating),2) AS avg_rating
FROM cust_shop_beha
GROUP BY Item_Purchased
ORDER BY ROUND(AVG(review_rating),2) DESC

--  *** WE CAN DO 'AVG(review_rating :: numeric)' for convert the review rating column into numeric

--  Q4. Compare the average purchase amounts between standered and Express shipping 
SELECT 
	Shipping_Type,AVG(Purchase_Amount_USD) Avg_purchase
FROM cust_shop_beha
WHERE Shipping_Type IN ('Standard','Express')
GROUP BY Shipping_Type
ORDER BY AVG(purchase_amount_usd) DESC


--  Q5. Do subscribe customers spend more? Compare average spend and total revenue between subscribers and non-subscribers/
SELECT 
	Subscription_Status,
	COUNT(customer_id) AS Total_customers,
	AVG(Purchase_Amount_USD) AS Avg_spend,
	SUM(Purchase_Amount_USD) AS Total_revenue
FROM cust_shop_beha
GROUP BY Subscription_Status
ORDER BY SUM(Purchase_Amount_USD) DESC

--  Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
	Item_Purchased,
	ROUND(100 * (SUM(CASE Discount_Applied WHEN  'Yes' THEN 1 ELSE 0 END))/ COUNT(*),2) AS discount_rate
FROM cust_shop_beha
GROUP BY Item_Purchased
ORDER BY discount_rate DESC


--  Q7. Segment customers into New , Retruening , and Loyal based on their total number of previous purchases  
with customer_type AS 
(SELECT 
	Customer_ID,
	previous_purchases,
	CASE  
		WHEN previous_purchases = 1 THEN 'New'
		WHEN Previous_Purchases BETWEEN 2 AND 10  THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
FROM cust_shop_beha
)
SELECT 
	customer_segment,count(customer_segment) AS Total_customers  
FROM customer_type
GROUP BY customer_segment
ORDER BY count(customer_segment) DESC;

-- Q8. What are the top 3 most purchased products within each category?
with item_purchased AS 
(	
	SELECT 
		Category,
		Item_Purchased, 
		COUNT(Item_Purchased)  AS Num_of_orders,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rn
	FROM cust_shop_beha
	GROUP BY Category,Item_Purchased
)

SELECT 
	Category,
	Item_Purchased,
	Num_of_orders
FROM item_purchased
WHERE rn IN (1,2,3)
SELECT TOP 10 * FROM cust_shop_beha

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscriber?
SELECT 
	'Total number of customers who are subscriber and also repeat buyers' AS Context,
	count(customer_id) AS Total_customers
FROM cust_shop_beha
WHERE Previous_Purchases > 5 AND Subscription_Status = 'Yes'
UNION ALL
SELECT 
	'Total number of customers who are subscriber but not repeat buyers' AS Context,
	count(customer_id) AS Total_customers
FROM cust_shop_beha
WHERE Previous_Purchases < 5 AND Subscription_Status = 'Yes'
UNION ALL 
SELECT 
	'Total number of customers who are not subscriber but repeat buyers' AS Context,
	count(customer_id) AS Total_customers
FROM cust_shop_beha
WHERE Previous_Purchases > 5 AND Subscription_Status = 'No'

 
-- Q10. What is the revenue contribution of each age group?

WITH age_contri AS 
(
	SELECT 
		CASE 
		 WHEN AGE <18 THEN 'Teenager'
		 WHEN AGE BETWEEN 18 AND 30 THEN 'Adult'
		 WHEN AGE BETWEEN 31 AND 50 THEN 'Senior'
		 ELSE 'Senior Citizen'
	END age_group,
		purchase_amount_usd AS Total_revenue
	FROM cust_shop_beha

)

SELECT 
	age_group,
	SUM(Total_revenue)
FROM age_contri
GROUP BY age_group
ORDER BY SUM(total_revenue) DESC



































